ALTER TABLE objects ADD COLUMN IF NOT EXISTS project_finance BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE objects ADD COLUMN IF NOT EXISTS project_finance_amount NUMERIC(14,2) DEFAULT 0;
ALTER TABLE objects ADD COLUMN IF NOT EXISTS completion_type VARCHAR(100);