ALTER TABLE app_users ADD COLUMN IF NOT EXISTS failed_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS first_failed_at TIMESTAMP;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP;